# seed: 42
seed_everything: 42

trainer:
  max_epochs: 300
  accelerator: gpu
  enable_checkpointing: true
  log_every_n_steps: 50
  deterministic: false
  num_sanity_val_steps: 0
  # limit_train_batches: 5
  # limit_val_batches: 5
  # limit_test_batches: 5
  logger:
    class_path: swanlab.integration.pytorch_lightning.SwanLabLogger
    init_args:
      project: AAGNet_PL
      # logdir: D:\510431\code\aagnet\v2\output\swanlog
      logdir: .\v2\output\swanlog
  callbacks:
    - class_path: v2.callbacks.EMA.EMACallback
      init_args:
        decay: 0.9516951530106196 # 0.5 ** (1 / 14)

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_seg_acc_avg
        mode: max
        save_top_k: 1
        #dirpath: D:\510431\code\aagnet\v2\output\checkpoints
        dirpath: .\v2\output\checkpoints\pretrain_MFTRCAD
        filename: "{epoch}-{val_seg_acc_avg:.2f}"
        save_last: true

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_seg_acc_avg
        mode: max
        patience: 60
        min_delta: 0.0001

model:
  num_classes: 27                 
  arch: AAGNetGraphEncoder
  edge_attr_dim: 15
  node_attr_dim: 14
  edge_attr_emb: 64
  node_attr_emb: 64
  edge_grid_dim: 0
  node_grid_dim: 7
  edge_grid_emb: 0
  node_grid_emb: 64
  num_layers: 3
  delta: 2
  mlp_ratio: 2
  drop: 0.10
  drop_path: 0.05
  head_hidden_dim: 64
  conv_on_edge: false
  use_uv_gird: true
  use_edge_attr: true
  use_face_attr: true
  lr: 3e-3
  weight_decay: 1e-4
  n_epochs: 300
  loss_type: ce
  focal_gamma: 1.5
  # use_class_weight: false
  # class_samples: None

data:
  root_dir: .\v2\data\MFTRCAD
  normalize: False
  center_and_scale: true
  random_rotate: False
  transform: null
  batch_size: 16
  shuffle: False # TODO need to be deleted in datamodule
  drop_last: False
  num_workers: 4
  prefetch_factor: 4
  label_names:
    - Chamfer
    - Through_hole
    - Triangular_passage
    - Rectangular_passage
    - Six_sided_passage
    - Triangular_through_slot
    - Rectangular_through_slot
    - Circular_through_slot
    - Rectangular_through_step
    - Two_sided_through_step
    - Slanted_through_step
    - O_ring
    - Blind_hole
    - Triangular_pocket
    - Rectangular_pocket
    - Six_sided_pocket
    - Circular_end_pocket
    - Rectangular_blind_slot
    - Vertical_circular_end_blind_slot
    - Horizontal_circular_end_blind_slot
    - Triangular_blind_step
    - Circular_blind_step
    - Rectangular_blind_step
    - Round
    - Plane
    - Cylinder
    - Cone
